import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';

import { AppScreen, useAppTheme } from '@/components/app-screen';
import { Card, EditorialHeader, Pill, PrimaryButton, SectionTitle } from '@/components/homiez-ui';
import { typography } from '@/constants/design';
import { formatMoney } from '@/lib/money';
import { useHousehold } from '@/providers/household-provider';

function RouteMap({ nodes = 3 }: { nodes?: number }) { const theme = useAppTheme(); return <View style={{ flexDirection: 'row', alignItems: 'center', gap: 7, padding: 12, borderRadius: 19, backgroundColor: theme.background }}>{Array.from({ length: nodes }).map((_, index) => <View key={index} style={{ flexDirection: 'row', alignItems: 'center', gap: 7 }}>{index ? <View style={{ width: 20, height: 2, backgroundColor: theme.faint }} /> : null}<View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: index === 1 ? theme.soft : theme.accent }} /></View>)}</View>; }
export default function DebtDetoxScreen() {
  const theme = useAppTheme(); const { data, debtPreview, acceptDebtPlan, confirmSettlementPayment } = useHousehold(); const [showMath, setShowMath] = useState(false);
  function accept() { acceptDebtPlan(); Alert.alert('Settlement plan saved', 'Every raw expense stays in the audit trail. Homiez records instructions only—it never moves money.', [{ text: 'Done', onPress: () => router.back() }]); }
  const activeBalances = debtPreview.balances.filter((balance) => data.members.find((member) => member.id === balance.memberId)?.status === 'active');
  return <AppScreen><EditorialHeader eyebrow="On-demand clarity" title="The shortest path to even." description="Every assumption stays visible. Homiez never moves funds." />
    <Card accent={theme.accent} variant="elevated" style={{ padding: 20 }}><Pill tone="pending">SIMPLIFIED PLAN</Pill><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}><View><Text style={{ color: theme.muted, fontFamily: typography.semibold, fontSize: 11 }}>MESSY IOUS BECOME</Text><Text selectable style={{ color: theme.heading, fontFamily: typography.extraBold, fontSize: 52, lineHeight: 57 }}>{debtPreview.transactions.length}</Text><Text selectable style={{ color: theme.muted, fontSize: 12 }}>direct payments</Text></View><RouteMap /></View></Card>
    <View style={{ gap: 10 }}><SectionTitle title="The clean route" action={`${debtPreview.transactions.length} steps`} />{debtPreview.transactions.length ? debtPreview.transactions.map((transaction, index) => <Card key={`${transaction.fromId}-${transaction.toId}`} style={{ padding: 14 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><View style={{ width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: theme.cardStrong }}><Text style={{ color: theme.heading, fontFamily: typography.semibold, fontSize: 18 }}>{String(index + 1).padStart(2, '0')}</Text></View><View style={{ flex: 1 }}><Text selectable style={{ color: theme.heading, fontFamily: typography.semibold, fontSize: 14 }}>{transaction.fromName} → {transaction.toName}</Text><Text selectable style={{ color: theme.muted, fontSize: 11, marginTop: 4 }}>One direct external payment</Text></View><Text selectable style={{ color: theme.accent, fontFamily: typography.bold, fontSize: 17 }}>{formatMoney(transaction.amountCents)}</Text></View></Card>) : <Card><Text selectable style={{ color: theme.accent, fontFamily: typography.semibold }}>Everyone is already square.</Text></Card>}</View>
    <View style={{ gap: 12 }}><SectionTitle title="Net positions" /><View style={{ flexDirection: 'row' }}>{activeBalances.map((balance, index) => <View key={balance.memberId} style={{ flex: 1, paddingLeft: index ? 13 : 0, paddingRight: 8, boxShadow: index ? 'inset 1px 0 rgba(255,255,255,.055)' : undefined }}><Text selectable numberOfLines={1} style={{ color: theme.faint, fontFamily: typography.bold, fontSize: 9 }}>{balance.name.toUpperCase()}</Text><Text selectable numberOfLines={1} style={{ color: balance.cents >= 0 ? theme.accent : theme.heading, fontFamily: typography.semibold, fontSize: 20, marginTop: 10 }}>{balance.cents > 0 ? '+' : balance.cents < 0 ? '−' : ''}{formatMoney(Math.abs(balance.cents))}</Text><Text style={{ color: theme.muted, fontSize: 9, marginTop: 4 }}>{balance.cents > 0 ? 'is owed' : balance.cents < 0 ? 'owes' : 'square'}</Text></View>)}</View></View>
    <Pressable onPress={() => setShowMath((value) => !value)}><Card variant="inset"><View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><View style={{ flex: 1 }}><Text selectable style={{ color: theme.heading, fontFamily: typography.semibold, fontSize: 14 }}>Show every line of math</Text><Text selectable style={{ color: theme.muted, fontSize: 11, marginTop: 4 }}>Net positions first, direct matching second.</Text></View><View style={{ width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: theme.cardStrong }}><Text style={{ color: theme.heading, fontSize: 22 }}>{showMath ? '−' : '+'}</Text></View></View>{showMath ? <View style={{ gap: 10 }}>{debtPreview.mathSteps.map((step, index) => <View key={`${index}-${step}`} style={{ flexDirection: 'row', gap: 10 }}><Text style={{ color: theme.accent, fontFamily: typography.bold }}>{index + 1}.</Text><Text selectable style={{ color: theme.muted, flex: 1, fontSize: 12, lineHeight: 18 }}>{step}</Text></View>)}</View> : null}</Card></Pressable>
    {data.settlement?.transactions.length ? <View style={{ gap: 10 }}><SectionTitle title="External confirmations" />{data.settlement.transactions.map((transaction) => { const payer = data.members.find((m) => m.id === transaction.fromId); const recipient = data.members.find((m) => m.id === transaction.toId); const canConfirm = transaction.status === 'pending' && transaction.fromId === data.currentUserId; return <Card key={transaction.id}><Text selectable style={{ color: theme.heading, fontFamily: typography.semibold }}>{payer?.name} → {recipient?.name}</Text><Text selectable style={{ color: theme.muted, fontSize: 11 }}>{formatMoney(transaction.amountCents)} · {transaction.status}</Text>{canConfirm ? <PrimaryButton label="Confirm external payment" icon="check" onPress={() => confirmSettlementPayment(transaction.id)} /> : null}</Card>; })}</View> : null}
    <PrimaryButton label={debtPreview.transactions.length ? 'Accept this payout plan' : 'Return to ledger'} icon="check" onPress={debtPreview.transactions.length ? accept : () => router.back()} />
  </AppScreen>;
}
